<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net48;net8.0</TargetFrameworks>
    <AssemblyName>LTRData.Cabinet</AssemblyName>
    <RootNamespace>LTRData.Cabinet</RootNamespace>
    <PackageId>LTRData.Cabinet</PackageId>
    <Description>Managed, cross-platform reader for Microsoft Cabinet archives.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/LTRData/Cabinet</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>$(NoWarn);1591</NoWarn>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' != 'net8.0'">
    <PackageReference Include="System.Memory" Version="4.5.5" />
  </ItemGroup>
</Project>
